language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - pytest