name: Coverage
# Runs tests, then does coverage checks. I don't do coverage checks in the main testing
# action, since I have a matrix there to run on various python versions.
# I only need to check coverage once. Most of this duplicates test.yaml
on: ["push"]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: install bpl
        run: pip install -e .[test]
      - name: download fonts
        run: python -c "import betterplotlib as bpl; bpl.set_style()"
      - name: run pytest
        run: coverage run -m pytest
      - name: make lcov file for Coveralls upload
        run: coverage lcov -i
      - name: upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
